version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
    volumes:
      - ./apps/backend:/usr/interact-backend
      - /usr/interact-backend/node_modules
    command: ["npm", "run", "dev"]
