/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AboutImport } from './routes/about';
import { Route as AdminImport } from './routes/admin';
import { Route as DashboardImport } from './routes/dashboard';
import { Route as IndexImport } from './routes/index';
import { Route as LoginImport } from './routes/login';
import { Route as ProfilImport } from './routes/profil';
import { Route as RegisterImport } from './routes/register';
import { Route as ShowsImport } from './routes/shows';

// Create/Update Routes

const ShowsRoute = ShowsImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any);

const ProfilRoute = ProfilImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/profil': {
      id: '/profil';
      path: '/profil';
      fullPath: '/profil';
      preLoaderRoute: typeof ProfilImport;
      parentRoute: typeof rootRoute;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    '/shows': {
      id: '/shows';
      path: '/shows';
      fullPath: '/shows';
      preLoaderRoute: typeof ShowsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/admin': typeof AdminRoute;
  '/dashboard': typeof DashboardRoute;
  '/login': typeof LoginRoute;
  '/profil': typeof ProfilRoute;
  '/register': typeof RegisterRoute;
  '/shows': typeof ShowsRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/admin': typeof AdminRoute;
  '/dashboard': typeof DashboardRoute;
  '/login': typeof LoginRoute;
  '/profil': typeof ProfilRoute;
  '/register': typeof RegisterRoute;
  '/shows': typeof ShowsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/admin': typeof AdminRoute;
  '/dashboard': typeof DashboardRoute;
  '/login': typeof LoginRoute;
  '/profil': typeof ProfilRoute;
  '/register': typeof RegisterRoute;
  '/shows': typeof ShowsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profil'
    | '/register'
    | '/shows';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profil'
    | '/register'
    | '/shows';
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profil'
    | '/register'
    | '/shows';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AdminRoute: typeof AdminRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  ProfilRoute: typeof ProfilRoute;
  RegisterRoute: typeof RegisterRoute;
  ShowsRoute: typeof ShowsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  RegisterRoute: RegisterRoute,
  ShowsRoute: ShowsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin",
        "/dashboard",
        "/login",
        "/profil",
        "/register",
        "/shows"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profil": {
      "filePath": "profil.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/shows": {
      "filePath": "shows.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
